name: financial_and_tax_planning_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  toast: ^0.1.5
  provider: ^4.0.4
  firebase_core: ^0.4.4+3
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  firebase_messaging: ^6.0.13
  google_sign_in: ^4.2.0
  responsive_grid: ^1.1.1
  material_design_icons_flutter: ^3.4.4995
  webview_flutter: ^0.3.19+8
  auto_size_text: ^2.1.0
  flushbar: 1.10.4
  flutter_spinkit: "^4.1.2"
  google_fonts: ^0.3.10
  simple_animations: ^1.3.11
  page_transition: ^1.1.5
  characters: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
          - asset: asset/fonts/Montserrat-Regular.ttf
    - family: MyIcons
      fonts:
          - asset: asset/icons/MyIcons.ttf
    - family: CategoriesIcon
      fonts:
          - asset: asset/icons/CategoriesIcon.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
